"""Add content_templates and schedule_settings to user

Revision ID: 7ba42cfd4769
Revises: 6f64dd6329b4
Create Date: 2025-07-02 14:10:21.024070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba42cfd4769'
down_revision: Union[str, Sequence[str], None] = '6f64dd6329b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
